# Generated by Django 2.2.5 on 2019-09-27 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import loteriaUruguayaAPI.apps.api.fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=50, unique=True)),
                ('game_created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('game_updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('game_has_unique_result_per_day', models.BooleanField()),
            ],
            options={
                'ordering': ['-game_id', '-game_created_at'],
            },
        ),
        migrations.CreateModel(
            name='VespertineNocturneResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_date', models.DateField(default=django.utils.timezone.now)),
                ('result_created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('result_updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('vn_result_is_vespertine', models.BooleanField()),
                ('result_game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn_result', to='api.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CincoDeOroResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_date', models.DateField(default=django.utils.timezone.now)),
                ('result_created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('result_updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('first_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
                ('second_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
                ('third_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
                ('fourth_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
                ('fifth_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
                ('sixth_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
                ('result_game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinco_de_oro_result', to='api.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
