# Generated by Django 2.2.5 on 2019-09-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_update_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_update_time',
        ),
    ]
