# Generated by Django 2.2.5 on 2019-09-25 14:01

from django.db import migrations, models
import django.db.models.deletion
import loteriaUruguayaAPI.apps.api.fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190925_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='CincoDeOroResult',
            fields=[
                ('result_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Result')),
                ('first_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
                ('second_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
                ('third_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
                ('fourth_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
                ('fifth_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
                ('sixth_ball', loteriaUruguayaAPI.apps.api.fields.fields.IntegerRangeField()),
            ],
            bases=('api.result',),
        ),
    ]
